
name: rpg_life_app
version: 1.0.0+1
description: RPG-приложение для саморазвития в стиле игры.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  fl_chart: ^0.60.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
